Allow unmount for fs_t to neutron
redhat-openstack/openstack-selinux pull request #71
Opened 2020-10-29 22:44 UTC by tobias-urdin

The DHCP agent fails on CentOS 8 with a
the standard 4.18 kernel.

The error from neutron-dhcp-agent:
2020-10-29 03:49:45.311 289412 ERROR neutron.agent.dhcp.agent [req-b3b5807e-c3de-4a7d-98a1-d1a067c9dba7 - - - - -] Unable to disable dhcp for db4a4385-2e44-44a3-a002-754cc2b44ae2.: OSError: [Errno 16] Device or resource busy
2020-10-29 03:49:45.311 289412 ERROR neutron.agent.dhcp.agent Traceback (most recent call last):
2020-10-29 03:49:45.311 289412 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python3.6/site-packages/neutron/agent/dhcp/agent.py", line 161, in call_driver
2020-10-29 03:49:45.311 289412 ERROR neutron.agent.dhcp.agent     getattr(driver, action)(**action_kwargs)
2020-10-29 03:49:45.311 289412 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python3.6/site-packages/neutron/agent/linux/dhcp.py", line 255, in disable
2020-10-29 03:49:45.311 289412 ERROR neutron.agent.dhcp.agent     self._destroy_namespace_and_port()
2020-10-29 03:49:45.311 289412 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python3.6/site-packages/neutron/agent/linux/dhcp.py", line 266, in _destroy_namespace_and_port
2020-10-29 03:49:45.311 289412 ERROR neutron.agent.dhcp.agent     ip_lib.delete_network_namespace(self.network.namespace)
2020-10-29 03:49:45.311 289412 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python3.6/site-packages/neutron/agent/linux/ip_lib.py", line 913, in delete_network_namespace
2020-10-29 03:49:45.311 289412 ERROR neutron.agent.dhcp.agent     privileged.remove_netns(namespace, **kwargs)
2020-10-29 03:49:45.311 289412 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python3.6/site-packages/oslo_privsep/priv_context.py", line 245, in _wrap
2020-10-29 03:49:45.311 289412 ERROR neutron.agent.dhcp.agent     return self.channel.remote_call(name, args, kwargs)
2020-10-29 03:49:45.311 289412 ERROR neutron.agent.dhcp.agent   File "/usr/lib/python3.6/site-packages/oslo_privsep/daemon.py", line 204, in remote_call
2020-10-29 03:49:45.311 289412 ERROR neutron.agent.dhcp.agent     raise exc_type(*result[2])
2020-10-29 03:49:45.311 289412 ERROR neutron.agent.dhcp.agent OSError: [Errno 16] Device or resource busy

The error from audit log:
type=AVC msg=audit(1604010639.062:643445): avc:  denied  { unmount } for  pid=753263 comm="privsep-helper" scontext=system_u:system_r:neutron_t:s0 tcontext=system_u:object_r:fs_t:s0 tclass=filesystem permissive=0
type=AVC msg=audit(1604010639.098:643446): avc:  denied  { unmount } for  pid=753263 comm="privsep-helper" scontext=system_u:system_r:neutron_t:s0 tcontext=system_u:object_r:fs_t:s0 tclass=filesystem permissive=0
type=AVC msg=audit(1604010639.922:643449): avc:  denied  { unmount } for  pid=753263 comm="privsep-helper" scontext=system_u:system_r:neutron_t:s0 tcontext=system_u:object_r:fs_t:s0 tclass=filesystem permissive=1

type=PATH msg=audit(1604010640.165:684660): item=0 name="/var/run/netns/qdhcp-db4a4385-2e44-44a3-a002-754cc2b44ae2" inode=4026533623 dev=00:03 mode=0100444 ouid=0 ogid=0 rdev=00:00 obj=system_u:system_r:neutron_t:s0 nametype=NORMAL cap_fe=? cap_fver=? cap_fp=? cap_fi=?OUID="root" OGID="root"
type=AVC msg=audit(1604010640.203:684661): avc:  denied  { unmount } for  pid=932089 comm="privsep-helper" scontext=system_u:system_r:neutron_t:s0 tcontext=system_u:object_r:fs_t:s0 tclass=filesystem permissive=0
type=SYSCALL msg=audit(1604010640.203:684661): arch=c000003e syscall=166 success=no exit=-13 a0=7fa614972290 a1=2 a2=7fa61d7d0000 a3=7fa6147f9120 items=1 ppid=1 pid=932089 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="privsep-helper" exe="/usr/libexec/platform-python3.6" subj=system_u:system_r:neutron_t:s0 key=(null)ARCH=x86_64 SYSCALL=umount2 AUID="unset" UID="root" GID="root" EUID="root" SUID="root" FSUID="root" EGID="root" SGID="root" FSGID="root"

2020-10-30 09:58 UTC, jpichon requested changes
Type definition is missing, LGTM otherwise! Thanks for the detailed PR message and including the AVC denials in it, I'll add them to the tests.

2020-10-30 09:58 UTC, jpichon commented on os-neutron.te
> +allow neutron_t fs_t:filesystem unmount;
fs_t needs to be added to the type definitions on top.

2020-10-30 10:03 UTC, jpichon commented
Or feel free to add the tests file yourself if you like, opened https://bugzilla.redhat.com/show_bug.cgi?id=1893132 for it

2020-10-30 19:19 UTC, tobias-urdin commented
Thanks @jpichon! I've updated, if it isn't much trouble a release when it merged as well :)

2020-11-02 09:41 UTC, jpichon approved these changes
Looking good! Thank you

2020-11-02 09:41 UTC, merged

2020-11-02 09:48 UTC, jpichon commented
Tagged as 0.8.24