Swift: Fix access to recon files
redhat-openstack/openstack-selinux pull request #83
Opened 2022-02-04 11:55 UTC by kajinamit

We've seen bunch of selinux denials from swift-container-replicator to
its recon data file, /var/cache/swift/container.recon when swift-
container-sharder is enabled.

This ensures swift processes have access allowed to the recon data
files to avoid such denials.

Resolves: rhbz#2050636

2022-02-04 12:07 UTC, kajinamit commented
@cjeanner May I ask you to check this when you have time ? Honestly I'm not very clear about the root cause and what I'm proposing here might be completely wrong.

2022-02-04 12:17 UTC, cjeanner commented
According to the denials listed in the associated BZ, it's not swift_var_cache_t, but var_t

It's weird, because this openstack-selinux package [has a specific entry setting the location as swift_var_cache_t](https://github.com/redhat-openstack/openstack-selinux/blob/7211283cb180f62fddbfc5d06b59cb95c442060f/local_settings.sh.in#L36).

Are those issues reported against cs9 or rhel9? If so, it's more than probably due to the removal of "lockdown" class from selinux-policy, preventing container-selinux to properly install, and preventing in the end the openstack-selinux package to install.

Care to check? In the meanwhile, I'm against merging this change, since it's:
- not fixing the actual issue (target type mismatch)
- more than probably useless once we get the openstack-selinux package in place

@jpichon do you agree?

2022-02-04 12:27 UTC, kajinamit commented
Just adding [WIP] tag, to avoid accidental merge. Maybe we can continue discussing details in bz, but let me put some initial responses here.

-  This issue is observed in both CentOS8 Stream and CentOS9 Stream.
-  I haven't tried RHEL8 or RHEL9
- The policy you mentioned was properly installed (If I read the log below correctly)
```
type=USER_MAC_CONFIG_CHANGE msg=audit(1643964279.372:3873): pid=56560 uid=0 auid=1000 ses=1 subj=unconfined_u:unconfined_r:semanage_t:s0-s0:c0.c1023 msg='resrc=fcontext op=add tglob="/var/cache/swift(/.*)" ftype=any tcontext=system_u:object_r:swift_var_cache_t: comm="semanage" exe="/usr/libexec/platform-python3.6" hostname=? addr=? terminal=? res=success'^]UID="root" AUID="zuul"
```

2022-02-04 13:15 UTC, jpichon requested changes
Agreed on not merging as this doesn't resolve the denials mentioned in the linked bug. Additionally, once we have a working rule the patch should be updated with a test file that includes the denials (see the other examples under /tests/) to prove that the rule works and avoid regressions in the future.

2022-02-05 08:35 UTC, kajinamit commented
I'll close this one because I totally agree what I'm proposing here is not likely to be effective.
I'll open a separate PR to fix the wrong selinux type of the directory itself.

2022-02-05 08:35 UTC, closed without merging